In [229]:
import pandas as pd
import numpy as np
import seaborn as sns
import matplotlib.pyplot as plt
pd.set_option('display.float_format','{:,.0f}'.format)

In [230]:
df_antioquia=pd.read_csv('Datos_obtenidos/antioquia.csv') # creación dataframes
df_risaralda=pd.read_csv('Datos_obtenidos/risaralda.csv')
df_caldas=pd.read_csv('Datos_obtenidos/caldas.csv')
df_quindio=pd.read_csv('Datos_obtenidos/quindio.csv')
list_df=[df_antioquia,df_risaralda,df_caldas,df_quindio]

In [231]:
df_quindio.columns

Index(['Unnamed: 0', 'Marca', 'Modelo', 'Año', 'Color', 'Tipo de combustible',
       'Puertas', 'Transmisión', 'Motor', 'Tipo de carrocería', 'Kilómetros',
       'Precio', 'Link', 'Ubicación'],
      dtype='object')

In [232]:
df_total=pd.DataFrame(columns=['Unnamed: 0', 'Marca', 'Modelo', 'Año', 'Color', 'Tipo de combustible',
       'Puertas', 'Transmisión', 'Motor', 'Tipo de carrocería', 'Kilómetros',
       'Precio', 'Link', 'Ubicación'])
for i in list_df: #se unen todos los dataframes para crear un dataframe total
       df_total=pd.concat([df_total,i])
df_total.drop(columns='Unnamed: 0', inplace=True)
df_total

,Marca,Modelo,Año,Color,Tipo de combustible,Puertas,Transmisión,Motor,Tipo de carrocería,Kilómetros,Precio,Link,Ubicación
0,Mercedes-Benz,Clase E,"2,016",Blanco,Gasolina,4,Automática,2.0,NaN,52000 km,115.000.000,https://carro.mercadolibre.com.co/MCO-91892983...,El Poblado - Medellín
1,Jeep,Wrangler,"2,014",Rojo,Gasolina,3,Mecánica,3.6,Camioneta,63900 km,134.200.000,https://carro.mercadolibre.com.co/MCO-91996256...,Las Lomitas - Sabaneta
2,Ford,Explorer,"2,014",Negro,Gasolina,5,Automática,3.5,Camioneta,85000 km,82.000.000,https://carro.mercadolibre.com.co/MCO-91891736...,Zuñiga - Envigado
3,Nissan,Frontier,"2,022",Gris,Diésel,4,Automática,2.5,Camioneta,5206 km,199.900.000,https://carro.mercadolibre.com.co/MCO-92138424...,Belén Fátima - Medellín
4,Mitsubishi,Montero,"2,004",Plateado,Gasolina,4,Mecánica,3.0,Camioneta,144578 km,55.000.000,https://carro.mercadolibre.com.co/MCO-91996844...,Belén Loma de los Bernal - Medellín
...,...,...,...,...,...,...,...,...,...,...,...,...,...
379,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,https://carro.mercadolibre.com.co/MCO-92336428...,Armenia
380,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,https://carro.mercadolibre.com.co/MCO-92659731...,Armenia
381,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,https://carro.mercadolibre.com.co/MCO-88809464...,Armenia
382,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,https://carro.mercadolibre.com.co/MCO-93773862...,Armenia
383,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,https://carro.mercadolibre.com.co/MCO-93361515...,Armenia

In [233]:
df_total.info() # se analiza la información que se obtiene

<class 'pandas.core.frame.DataFrame'>
Int64Index: 4800 entries, 0 to 383
Data columns (total 13 columns):
 #   Column               Non-Null Count  Dtype
---  ------               --------------  -----
 0   Marca                3121 non-null   object
 1   Modelo               3121 non-null   object
 2   Año                  3121 non-null   float64
 3   Color                3121 non-null   object
 4   Tipo de combustible  3121 non-null   object
 5   Puertas              3121 non-null   object
 6   Transmisión          3121 non-null   object
 7   Motor                3121 non-null   object
 8   Tipo de carrocería   2064 non-null   object
 9   Kilómetros           3121 non-null   object
 10  Precio               3121 non-null   object
 11  Link                 4800 non-null   object
 12  Ubicación            4800 non-null   object
dtypes: float64(1), object(12)
memory usage: 525.0+ KB

In [234]:
valid=df_total.notnull() # elimino los valores que no tiene información
df_total=df_total[valid.Marca]
df_total
df_total_clean=df_total.copy()

In [235]:
df_total_clean['Precio']=df_total_clean['Precio'].str.replace('.','', regex=True) # a partir de aca se edita la información para ser utilizada, cambiamos tipos de datos y eliminamos datos que no sirvan.
df_total_clean['Kilómetros']=df_total_clean['Kilómetros'].str.replace(' km','', regex=True)
df_total_clean = df_total_clean.astype({"Año": int, "Kilómetros": float,'Precio':float})# transofrmación de datos a enteros

In [236]:
df_total_clean

,Marca,Modelo,Año,Color,Tipo de combustible,Puertas,Transmisión,Motor,Tipo de carrocería,Kilómetros,Precio,Link,Ubicación
0,Mercedes-Benz,Clase E,2016,Blanco,Gasolina,4,Automática,2.0,NaN,"52,000","115,000,000",https://carro.mercadolibre.com.co/MCO-91892983...,El Poblado - Medellín
1,Jeep,Wrangler,2014,Rojo,Gasolina,3,Mecánica,3.6,Camioneta,"63,900","134,200,000",https://carro.mercadolibre.com.co/MCO-91996256...,Las Lomitas - Sabaneta
2,Ford,Explorer,2014,Negro,Gasolina,5,Automática,3.5,Camioneta,"85,000","82,000,000",https://carro.mercadolibre.com.co/MCO-91891736...,Zuñiga - Envigado
3,Nissan,Frontier,2022,Gris,Diésel,4,Automática,2.5,Camioneta,"5,206","199,900,000",https://carro.mercadolibre.com.co/MCO-92138424...,Belén Fátima - Medellín
4,Mitsubishi,Montero,2004,Plateado,Gasolina,4,Mecánica,3.0,Camioneta,"144,578","55,000,000",https://carro.mercadolibre.com.co/MCO-91996844...,Belén Loma de los Bernal - Medellín
...,...,...,...,...,...,...,...,...,...,...,...,...,...
228,Volkswagen,Voyage,2020,Gris,Gasolina,4,Mecánica,1.6,Sedán,"22,000","45,000,000",https://carro.mercadolibre.com.co/MCO-93044302...,Armenia
229,Chevrolet,Onix,2016,Gasolina,5,Mecánica,1.4,Hatchback,NaN,"77,000","44,000,000",https://carro.mercadolibre.com.co/MCO-93185251...,Armenia
230,Chevrolet,Sonic,2015,Gasolina,4,Mecánica,1.6,Sedán,NaN,"97,000","37,000,000",https://carro.mercadolibre.com.co/MCO-61909666...,Armenia
231,Nissan,X-Trail,2014,Dorado,Gasolina,5,Mecánica,2.5,Camioneta,"89,839","65,000,000",https://carro.mercadolibre.com.co/MCO-61909667...,Armenia
232,Mitsubishi,L200 SPORTERO,2007,Diésel,2,Mecánica,2.5,Pick-Up,NaN,"288,000","60,000,000",https://carro.mercadolibre.com.co/MCO-91452414...,Armenia

In [237]:
df_total_clean['Tipo de combustible'].unique() # reviso valore unicos de Tipo de combustible para entender que pasa con esta columna.

array(['Gasolina', 'Diésel', 'Híbrido', 'Eléctrico', 'Gasolina y gas',
       '2', '4', '5', '3'], dtype=object)

In [238]:
sin_color=(df_total_clean['Tipo de combustible']=='2') | (df_total_clean['Tipo de combustible']=='4') | (df_total_clean['Tipo de combustible']=='5') | (df_total_clean['Tipo de combustible']=='3') 
#al revisar con este filtro vimos que no habia color en los carros, como para mi es un item importante eliminare esta columna y los filtraré más adelante

In [239]:
df_final_an=df_total_clean[~sin_color]
df_total_clean['Tipo de combustible'].unique() #Ya no hay valores distintos a Tipo de combustible.

array(['Gasolina', 'Diésel', 'Híbrido', 'Eléctrico', 'Gasolina y gas'],
      dtype=object)

In [240]:
df_final_an['Color'].unique()# todos son colores, no hay problema.

array(['Blanco', 'Rojo', 'Negro', 'Gris', 'Plateado', 'Marrón', 'Azul',
       'Amarillo', 'Beige', 'Verde', 'Naranja', 'Naranja Ocre',
       'Plata Sirius', 'Según Disponibilidad', 'Dorado', 'plata sirius',
       'Celeste', 'A elegir', 'Violeta', 'Habano Marfil',
       'GRIS PLATINO METALICO', 'BLANCO PERLADO'], dtype=object)

In [241]:
df_final_an['Puertas'].unique()

array(['4', '3', '5', '2', '7', '8'], dtype=object)

In [242]:
# a continuación haré todos los filtros segun mis necesidades.
precio=df_total_clean['Precio']<=55000000
kilometraje=df_total_clean['Kilómetros']<65000
modelo=df_total_clean['Año']>2014
df_final_an=df_final_an[precio & kilometraje & modelo]